Numpy

In [2]:
import numpy as np

Basics

In [3]:
array = np.array([1, 2, 3, 4])
array = array * 2
print(array)

[2 4 6 8]


In [4]:
array = np.array([[['A', 'B', 'C'], ['D', 'E', 'F'],['G', 'H', 'I']],
                  [['J', 'K', 'L'], ['M', 'N', 'O'],['P', 'Q', 'R']],
                  [['S', 'T', 'U'], ['V', 'W', 'X'],['Y', 'Z', '']]])

print(array.shape)

(3, 3, 3)


In [5]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [6]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [7]:
# Get Dimension
a.ndim

1

In [8]:
# Get Shape
a.shape

(3,)

In [9]:
# Get Size
a.itemsize

8

In [10]:
# Get Total Size
a.nbytes

24

In [11]:
# Size
b.itemsize

8

Accessing/Changing Specific Element From Specific Rows, Columns etc.

In [12]:
c = np.array([[1, 2, 3, 4, 5, 6, 7],[8, 9, 10, 11, 12, 13, 14]])
print(a)

[1 2 3]


In [13]:
# Accessing Specific Element (r, c)
print(c[1,5])

13


In [14]:
# Get a Specefic Row
c[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [15]:
# Get A Specific Column
c[:, 2]

array([ 3, 10])

In [16]:
np.arange(10, 30, 5)
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [17]:
# Getting Specific Element [srartinex:endindex:stepsize]
c[0, 1:6:2]

array([2, 4, 6])

In [18]:
# To change specific element
c[1,5] = 20
print(c)

c[:, 2] = 5
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [24]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [25]:
# Get specific (work outside in)
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [26]:
# Replace 
b[:,1,:] = [[9,9],[8,8]]

In [27]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

Initializing Different Types of Arrays

In [ ]:
# All 0s Matrix
np.zeros([2,3]) 

array([[0., 0., 0.],
       [0., 0., 0.]])

In [37]:
# All 1s Matrix
np.ones((2,3), dtype='int32')

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [32]:
# Any other number shape,number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [42]:
# Any other number (Full_Like)
np.full_like(c,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [44]:
# Random decimal numbers
# np.random.rand(2,4)
np.random.random_sample(c.shape)

array([[0.00718301, 0.88528508, 0.59509275, 0.32363189, 0.92638216,
        0.54503561, 0.39828736],
       [0.78430542, 0.20795292, 0.99766299, 0.26345035, 0.10407475,
        0.01247977, 0.94255801]])

In [45]:
# Random Integer values
np.random.randint(7, size=(3,3))

array([[0, 1, 5],
       [1, 0, 0],
       [5, 6, 2]], dtype=int32)

In [49]:
# Identity Matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [50]:
# Repeat an Array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [56]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
print(z)
z[1,1] = 9
print(z)

output[1:4, 1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Be careful when copying arrays

In [58]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


Mathematics


In [ ]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [60]:
a + 2

array([3, 4, 5])

In [61]:
a - 2

array([-1,  0,  1])

In [62]:
a * 2

array([2, 4, 6])

In [63]:
a / 2

array([0.5, 1. , 1.5])

In [64]:
a // 2

array([0, 1, 1])

In [66]:
b = np.array([1,0,1])
a + b

array([2, 2, 4])

In [67]:
a ** 2

array([1, 4, 9])

Linear Algebra

In [71]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [72]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

Statistics

In [73]:
stats = np.array([[1,2,3],[4,5,6]])
print(stats)


[[1 2 3]
 [4 5 6]]


In [78]:
np.min(stats)

np.int64(1)

In [76]:
np.max(stats)

np.int64(6)

In [79]:
np.sum(stats)

np.int64(21)

Reorganizing Arrays

In [83]:
# vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])